version: '{build}'

image: Visual Studio 2017

install:
- choco install opencppcoverage
- choco install codecov
- set path=C:\Program Files\OpenCppCoverage;%path%

platform:
- x64

configuration:
- Debug

before_build:
- mkdir build && cd build
- set PATH=C:\Qt\5.13.0\msvc2017_64\bin;%PATH%
- cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\IpcAdapter.sln

test_script:
- cd %APPVEYOR_BUILD_FOLDER%\build
- OpenCppCoverage.exe --export_type cobertura:coverage.xml --modules "*.exe" --cover_children --sources "*20_Sources*.cpp" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "*tst*" --excluded_sources "*qamqp*" -- ctest -C %CONFIGURATION% -V
- codecov -f coverage.xml --root %APPVEYOR_BUILD_FOLDER%
